/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#1b1833",
        "on-primary-fixed": "#00201a",
        "on-background": "#191c1c",
        "primary-container": "#52796f",
        "on-primary": "#ffffff",
        "surface-dim": "#d8dad9",
        "on-secondary-container": "#576661",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#c8c2e6",
        "tertiary-fixed": "#e4dfff",
        "surface-container": "#f1f6f4",
        "on-secondary-fixed-variant": "#3b4a45",
        "on-tertiary-fixed-variant": "#474361",
        "surface-container-highest": "#e4ebe8",
        "outline-variant": "#c0c8c5",
        "secondary-container": "#d3e3dd",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#fbf6ff",
        "primary-fixed": "#c1ebdf",
        "error": "#ba1a1a",
        "surface-container-low": "#f6faf8",
        "surface-bright": "#fcfdfc",
        "primary": "#3a6057",
        "on-primary-fixed-variant": "#274e45",
        "primary-fixed-dim": "#a6cfc3",
        "tertiary": "#595674",
        "on-surface": "#191c1c",
        "surface-container-high": "#ebf1ef",
        "secondary": "#52625d",
        "background": "#fcfdfc",
        "inverse-on-surface": "#eff1f0",
        "inverse-surface": "#2e3131",
        "surface-variant": "#e1e3e2",
        "secondary-fixed-dim": "#bacac4",
        "on-surface-variant": "#414846",
        "on-primary-container": "#dcfff4",
        "on-secondary-fixed": "#101e1b",
        "on-error": "#ffffff",
        "tertiary-container": "#726e8e",
        "outline": "#717976",
        "inverse-primary": "#a6cfc3",
        "surface-tint": "#3f665c",
        "secondary-fixed": "#d6e6e0",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface": "#fcfdfc"
      },
      fontFamily: {
        "headline": ["Pretendard", "Manrope"],
        "body": ["Pretendard", "Manrope"],
        "label": ["Pretendard", "Manrope"]
      },
      borderRadius: {
        "DEFAULT": "0.5rem", 
        "lg": "1rem", 
        "xl": "1.5rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
